### ISSUE TITLE
Version 0.14.0 CSS minifier broken font import handling

### ISSUE THREAD

**Issue by marvec** [W3EDGE/w3-total-cache#197]
This worked with the previous version. Now the only option is to disable CSS minification.
The bug: The page URL is prepended to the font file URL.

Tried setting minifiers to CSS Minify and Tidy CSS. Both produce the same result.

![image](https://user-images.githubusercontent.com/625319/83081989-5e821f00-a082-11ea-8eaa-1316b3aed73b.png)

**Comment by bwmarkle** [comment]
Hi @marvec - We're really sorry to hear about this issue. We're looking into it, and we'll touch base shortly.

Thanks,
\- Brad

**Comment by bwmarkle** [comment]
@cssjoe 

I've been able to replicate this issue.

---

1. Download [this raw .woff file](https://github.com/theleagueof/ostrich-sans/blob/master/webfonts/ostrich-sans-black.woff) to `wp-content/themes/twentytwenty/ostrich-sans-black.woff`
2. Edit `wp-content/themes/twentytwenty/style.css` and add the following to the top:
```css
@font-face {
    font-family: "ostrich sans black";
    src: url(http://YOUR-DOMAIN/wp-content/themes/twentytwenty/ostrich-sans-black.woff);
}

body {
    font-family: "ostrich sans black", arial, sans-serif !important;
}
```
3. Enable CSS minification and clear the caches.
4. Go to the front end of your site. You'll see the error.
5. Checkout the `.0.13.3` tag and clear your caches. Issue resolved.

---

The issue is with a full urls being used as the src.

This works:
```css
@font-face {
    font-family: "ostrich sans black";
    src: url(ostrich-sans-black.woff);
}
```

This does not work:
```css
@font-face {
    font-family: "ostrich sans black";
    src: url(http://YOUR-DOMAIN/wp-content/themes/twentytwenty/ostrich-sans-black.woff);
}
```
